# Adapted from https://github.com/numtide/nixpkgs-unfree/blob/main/.github/workflows/sync.yml

name: Sync channels

on: 
  schedule:
    - cron: "15 11 * * *" # daily
  workflow_dispatch: # on button click
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v15
    - name: configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - run: nix flake update
    - run: |
        if [[ -n $(git status --porcelain) ]]; then
          git commit -am "nix flake update"
          git push origin develop
        fi

